### PR TITLE
Check for USER_DN header before cert

### LINKED ISSUE #232: List based authorization does not work for impersonation and oauth.
The current implementation of the white and black listing logic only works directly on the client certificate presented to the service.  However, we have many deployments that use impersonation (i.e., the gateway terminates the client's SSL connection and uses it's own certificate for proxied traffic) and OAuth.  In these cases, the presented certificate is only valid for knowing what service is connecting to our service.  We need to know which user the service is impersonating.  The user is indicated in headers in these cases.  See https://github.com/DecipherNow/gm-data-fabric/blob/master/handler/http.go#L287.

### PR DESCRIPTION
**Pull request by dougfort**
closes #232

### CODE REVIEW

File: listauth/http.go [hunk 1]
```diff
@@ -53,7 +53,19 @@ func handlerFactory(
...
 		}
 
-		dn := tlsutil.GetDistinguishedName(r.TLS.PeerCertificates[0])
+		var dn string
+
+		// See Issue #232 List based authorization does not work for
+		// impersonation and oauth.
+		// If the user is being impersonated by a trusted proxy, we should get
+		// the original user name in a header.
+		// udn code copied from gm-data-fabric
```
Comment (joshua-rutherford) [inline listauth/http.go]: There is no reason to keep this linkage to the private repository from which this was sourced.
