### PR TITLE
Fix errors uncovered processing the swagger petstore api

### LINKED ISSUE #160: Correct fabric generator errors handling swagger Pet Store example
See #159 

This is intended to be tied to a PR correcting errors in the generator that are shown up by processing theis complicated protobuf file.

### PR DESCRIPTION
**Pull request by dougfort**
Closes #160

### CODE REVIEW

File: cmd/fabric/test_fabric.sh [hunk 1]
```diff
@@ -34,7 +34,7 @@ mkdir $TESTDIR
 SERVICE_NAME="test_service"
 
 # initialize the service
-fabric --log-level="debug" --dir="$TESTDIR" --template git@github.com:deciphernow/gm-fabric-templates.git//default?ref=20-minimum-version --init $SERVICE_NAME \
+fabric --log-level="debug" --dir="$TESTDIR" --init $SERVICE_NAME
```
Comment (joshua-rutherford) [inline cmd/fabric/test_fabric.sh]: Did you want to switch back to not using a template?

Comment (dougfort) [reply cmd/fabric/test_fabric.sh]: I'm trying to keep the checked in version clean. I run my tests with non-mater template typed in. Some times (actually most times) I slip and check in the modified test.

**Comment by joshua-rutherford** [comment]
@alecholmez or @cstrahan, can one of you approve this as doug and I both have our fingers on it.  @dougfort, i just cleaned up the commit log (should have done a rebase but I did it a faster way which puts my name on the commit so I can't approve anymore).
